server:
  port: ${SERVER_PORT:8090}
  shutdown: graceful

spring:
  main:
    banner-mode: off
  webflux:
    base-path: /api/v1
  application:
    name: mc-accounts
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/accounts}
    username: ${SPRING_R2DBC_USERNAME:accounts-user}
    password: ${SPRING_R2DBC_PWD:4cc0unt5P4ssw0rd!123}
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: "liquibase/changelog.yml"
    url: ${SPRING_LIQUIBASE_URL:jdbc:postgresql://localhost:5432/accounts}
    user: ${SPRING_LIQUIBASE_USERNAME:accounts-user}
    password: ${SPRING_LIQUIBASE_PWD:4cc0unt5P4ssw0rd!123}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "info,health,circuitbreakers"
  health:
    circuitbreakers:
      enabled: true

resilience4j.circuitbreaker:
  instances:
    accounts-client:
      register-health-indicator: true
      minimum-number-of-calls: 3
      sliding-window-type: TIME_BASED
      sliding-window-size: 6
      permitted-number-of-calls-in-half-open-state: 3

integrations:
  apis:
    baseUrlCustomers: ${APIS_BASE_PATH_CUSTOMERS:http://localhost:8091}
    baseUrlBacen: ${APIS_BASE_PATH_BACEN:http://localhost:8092}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
  pattern:
    console: "[%thread][%highlight(%-5level)][%cyan(%d{yyyy-MM-dd HH:mm:ss})][%yellow(%X{requestId})][%magenta(%logger{40})] - %message%n"